### ISSUE TITLE
Game Logic freezes after time

### ISSUE THREAD

**Issue by arne-fuchs** [ereb-thanatos/cossacks3-lan-server#11]
Hello,
I already made an issue like that before, but sadly didn't had the time to answer your question, so here I am uploading it, because the following bug is still present:

For a random player the game logic starts to freeze in midgame; he still seems to be connected but he can't do anything. Neither are his units moving or creating new ones. In the terminal of the program it still says, that he is connected.

**Comment by ereb-thanatos** [comment]
Hello.

> I already made an issue

#10 

> didn't had the time to answer your question

Apparently you still don't, otherwise you would have specified a game client version.

> because the following bug is still present

Of course it is. I am no longer developing this project.

I assume that there has been an update to the network protocol used in Cossacks 3. It could be intentional or by accident, but the new protocol is incompatible with my LAN server.

As I said, I am no longer working on this project. However I would accept a PR. Please feel free to investigate the issue. You could start by building the LAN server in debug mode, so that [the output of unknown messages](https://github.com/ereb-thanatos/cossacks3-lan-server/blob/master/src/Lobby.cpp#L1182) is enabled. This way you would see if there is a new message that breaks the game.

**Comment by arne-fuchs** [comment]
It is the version 2.2.3.92.6008.
I was thinking of reprogramming the server in java. May you have a guide or something like that where I can look for what I have to do?

**Comment by ereb-thanatos** [comment]
That's curious. The 2.1.4 server release was tested with the 2.2.3 client back when I was still working on it in 2018. I expected that there are new Cossacks 3 client versions around that are no longer compatible with the server. However if you are playing on a 2.2.3 things should be fine. I honestly can not help you here, sorry.

I have no firsthand experience with Java and cannot recommend any guides or resources on it. I wish you as much fun as I had writing this server. When you are done, open a PR for the readme to include a link to your new server ; )
