### ISSUE TITLE
Help for internet use with hamachi

### ISSUE THREAD

**Issue by thegametn** [ereb-thanatos/cossacks3-lan-server#4]
Hi,

Thanks for the LAN server.

Im trying to make it work over internet using hamachi. However it doesent work and i got the error "windows socket error 10061".

Anyone manage to use it with internet ?

Thank for helping

**Comment by tahsin002** [comment]
I have succeeded In playing Age of empires 2 and Rise of nations online through virtual LAN. I did not try with cossacks 3 because I want Multiplayer save. Without it I believe my efforts will be wasted as I won't play without that function. I used neorouter and Softether for virtual LAN. Currently using Neorouter. Do you need help setting them up?

**Comment by ereb-thanatos** [comment]
You are welcome. I understand your concern, but as you can see in the [readme notes](https://github.com/ereb-thanatos/cossacks3-lan-server#notes), I do not endorse the usage of my server over the internet. That's what the official server is there for.

Good luck and have fun
